services:
    admin.order:
        class: App\Admin\OrderAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Order, group: Admin }
        public: true

    admin.page:
        class: App\Admin\PageAdmin
        arguments: [~, App\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Page, group: Admin }
        public: true

    admin.param:
        class: App\Admin\ParamAdmin
        arguments: [~, App\Entity\Param, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Param, group: Admin }
        public: true