services:
    admin.order:
        class: App\Admin\OrderAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Order }
        public: true